#!/usr/bin/env python3
"""Generate icache_probe.cu: disambiguate what the ~128KB i-fetch cache is.

Experiment SMEM: same 6144-inst (96KB) straight-line body, launched with 0
vs ~99KB dynamic shared memory. If instruction fetch shares the unified
L1/shared array, the large carveout must crush the 96KB code footprint.

Experiment MULTI: one block, W warps; each warp jumps to its own disjoint
4096-inst (64KB) region. Combined footprint W*64KB. Locates the capacity
cliff from a second angle and shows the cache is shared across warps.
"""

BODY_N = 6144   # 96KB, comfortably inside the 128KB cliff
REGION_N = 4096  # 64KB per-warp region for MULTI


def emit_macros(lines, tag, const_hex, n):
    """REP macros for n instructions using immediate `const_hex` (distinct
    constants keep regions from being merged by the compiler)."""
    lines.append(f'#define A1_{tag}(i) asm volatile("add.f32 %0, %0, {const_hex};" : "+f"(x##i));')
    lines.append(f"#define A8_{tag} A1_{tag}(0) A1_{tag}(1) A1_{tag}(2) A1_{tag}(3) "
                 f"A1_{tag}(4) A1_{tag}(5) A1_{tag}(6) A1_{tag}(7)")
    prev, blk = f"A8_{tag}", 8
    while blk * 2 <= n:
        blk *= 2
        lines.append(f"#define R{blk}_{tag} {prev} {prev}")
        prev = f"R{blk}_{tag}"
    # compose exactly n
    parts, rest = [], n
    b = blk
    while b >= 8:
        name = f"A8_{tag}" if b == 8 else f"R{b}_{tag}"
        while rest >= b:
            parts.append(name)
            rest -= b
        b //= 2
    assert rest == 0
    return " ".join(parts)

lines = ["// auto-generated by icache_gen2.py",
         "#include <cstdio>",
         "#include <cuda_runtime.h>", ""]

DECL = ("    float x0 = 1.f, x1 = 1.f, x2 = 1.f, x3 = 1.f,\n"
        "          x4 = 1.f, x5 = 1.f, x6 = 1.f, x7 = 1.f;")

# --- SMEM experiment kernel: BODY_N insts + optional dynamic shared use
body_smem = emit_macros(lines, "S", "0f3F800000", BODY_N)
lines += [
    "",
    "extern __shared__ float smem[];",
    f"__global__ void __launch_bounds__(32) k_smem(unsigned long long *cyc, float *sink, int reps, int use_smem) {{",
    DECL,
    "    if (use_smem) smem[threadIdx.x] = 1.0f;",
    "    unsigned long long t0 = clock64();",
    "#pragma unroll 1",
    f"    for (int r = 0; r < reps; ++r) {{ {body_smem} }}",
    "    unsigned long long t1 = clock64();",
    "    if (threadIdx.x == 0) *cyc = t1 - t0;",
    "    float s = x0 + x1 + x2 + x3 + x4 + x5 + x6 + x7;",
    "    if (use_smem) s += smem[31 - threadIdx.x];",
    "    sink[threadIdx.x] = s;",
    "}",
]

# --- MULTI experiment kernel: 4 disjoint 64KB regions, one per warp
consts = ["0f3F800000", "0f3F000000", "0f3E800000", "0f3E000000"]
bodies = [emit_macros(lines, f"W{w}", consts[w], REGION_N) for w in range(4)]
lines += [
    "",
    "__global__ void __launch_bounds__(128) k_multi(unsigned long long *cyc, float *sink, int reps) {",
    DECL,
    "    int w = threadIdx.x >> 5;",
    "    unsigned long long t0 = clock64();",
]
for w in range(4):
    kw = "if" if w == 0 else "else if"
    lines += [f"    {kw} (w == {w}) {{",
              "#pragma unroll 1",
              f"        for (int r = 0; r < reps; ++r) {{ {bodies[w]} }}",
              "    }"]
lines += [
    "    unsigned long long t1 = clock64();",
    "    if ((threadIdx.x & 31) == 0) cyc[w] = t1 - t0;",
    "    sink[threadIdx.x] = x0 + x1 + x2 + x3 + x4 + x5 + x6 + x7;",
    "}",
]

# --- host
lines += [
    "",
    "int main(int argc, char **argv) {",
    "    int reps = argc > 1 ? atoi(argv[1]) : 64;",
    "    unsigned long long *cyc; float *sink; unsigned long long h[4];",
    "    cudaMalloc(&cyc, 4 * sizeof(unsigned long long));",
    "    cudaMalloc(&sink, 128 * sizeof(float));",
    "",
    "    int dev; cudaGetDevice(&dev);",
    "    int max_smem;",
    "    cudaDeviceGetAttribute(&max_smem, cudaDevAttrMaxSharedMemoryPerBlockOptin, dev);",
    '    printf("max dynamic smem/block: %d KB\\n", max_smem / 1024);',
    "    cudaFuncSetAttribute(k_smem, cudaFuncAttributeMaxDynamicSharedMemorySize, max_smem);",
    "",
    f'    printf("\\n[SMEM] body = {BODY_N} insts = {BODY_N * 16 // 1024} KB\\n");',
    "    for (int use = 0; use <= 1; ++use) {",
    "        size_t sz = use ? (size_t)max_smem : 0;",
    "        k_smem<<<1, 32, sz>>>(cyc, sink, reps, use);  // warmup",
    "        k_smem<<<1, 32, sz>>>(cyc, sink, reps, use);",
    "        cudaMemcpy(h, cyc, sizeof(h[0]), cudaMemcpyDeviceToHost);",
    f'        printf("  smem=%3zuKB  cyc/inst = %.3f\\n", sz / 1024, (double)h[0] / ((double){BODY_N} * reps));',
    "    }",
    "",
    f'    printf("\\n[MULTI] per-warp region = {REGION_N} insts = {REGION_N * 16 // 1024} KB\\n");',
    "    for (int W = 1; W <= 4; ++W) {",
    "        k_multi<<<1, W * 32>>>(cyc, sink, reps);  // warmup",
    "        k_multi<<<1, W * 32>>>(cyc, sink, reps);",
    "        cudaMemcpy(h, cyc, W * sizeof(h[0]), cudaMemcpyDeviceToHost);",
    "        double worst = 0;",
    f"        for (int w = 0; w < W; ++w) worst = max(worst, (double)h[w] / ((double){REGION_N} * reps));",
    f'        printf("  W=%d  footprint=%3dKB  worst cyc/inst = %.3f\\n", W, W * {REGION_N * 16 // 1024}, worst);',
    "    }",
    "    cudaError_t err = cudaGetLastError();",
    '    if (err != cudaSuccess) printf("ERROR: %s\\n", cudaGetErrorString(err));',
    "    return 0;",
    "}",
]

with open("icache_probe.cu", "w") as f:
    f.write("\n".join(lines) + "\n")
print("generated icache_probe.cu")
